# Generated by Django 5.0.6 on 2024-06-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mall', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('response', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ почтового сервера')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='main.client', verbose_name='Список клиентов'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing'),
        ),
    ]
