# Generated by Django 5.0.6 on 2024-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('active', 'Активна'), ('completed', 'Завершена')], max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
