# Generated by Django 5.0.6 on 2024-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='regularity',
            field=models.CharField(choices=[('day', 'Каждый день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], max_length=5, verbose_name='Периодичность'),
        ),
    ]
