# Generated by Django 5.0.6 on 2024-07-17 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailing_regularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='last_mall',
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_mall',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней отправки рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_mail',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей отправки рассылки'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 15, 49, 54, 594502, tzinfo=datetime.timezone.utc), verbose_name='Дата и время попытки'),
            preserve_default=False,
        ),
    ]
