# Generated by Django 4.2 on 2024-07-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_client_user_mailing_user_mailinglog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailings', 'Может отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
